name: Build and Package Extension

on:
  push:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install dependencies
        run: |
          cd extension
          npm install

      - name: Build the extension
        run: |
          cd extension
          npm run build

      - name: Create zip package
        run: |
          cd extension
          zip -r extension.zip ./*

      - name: Upload zip package
        uses: actions/upload-artifact@v2
        with:
          name: extension-package
          path: extension/extension.zip
          
      - name: Move built package to Packages directory
        run: |
          mkdir -p Packages
          mv extension/extension.zip Packages/
