name: Package and Release Extension

on:
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip Extension Folder
        run: |
          cd extension
          zip -r ../IP-Location-Finder.zip .
          cd ..

      - name: Upload ZIP Artifact
        uses: actions/upload-artifact@v4
        with:
          name: IP-Location-Finder-zip
          path: IP-Location-Finder.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download ZIP Artifact
        uses: actions/download-artifact@v4
        with:
            name: IP-Location-Finder-zip
            path: .

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.4
          release_name: Release v1.4
          body: |
            This release contains the packaged extension.
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: IP-Location-Finder.zip
            asset_name: IP-Location-Finder-v${{ github.run_number }}.zip
            asset_content_type: application/zip
