name: Build and Package Chrome Extension

on:
  push:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          
      - name: Install dependencies
        run: |
          cd extension
          npm install

      - name: Build the Chrome extension
        run: |
          cd extension
          npm run build

      - name: Create zip package for Chrome extension
        run: |
          cd extension
          zip -r chrome-extension.zip ./*

      - name: Upload zip package
        uses: actions/upload-artifact@v3
        with:
          name: chrome-extension-package
          path: extension/chrome-extension.zip
          
      - name: Move built package to Packages directory
        run: |
          mkdir -p Packages
          mv extension/chrome-extension.zip Packages/
