name: Build IP-Location-Finder Chrome Extension

on:
  push:
    branches:
      - main # Or the branch you use for releases
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Or your preferred node version

      - name: Install web-ext and chrome-pack
        run: npm install --global web-ext chrome-pack

      - name: Build ZIP
        run: |
          web-ext build \
            --artifacts-dir=dist \
            --source-dir=extension \
            --overwrite-dest \
            --filename="IP-Location-Finder.zip"

      - name: Convert ZIP to CRX
        run: |
          chrome-pack dist/IP-Location-Finder.zip dist/IP-Location-Finder.crx --pack-extension=false

      - name: Upload CRX
        uses: actions/upload-artifact@v4
        with:
          name: IP-Location-Finder-crx
          path: dist/IP-Location-Finder.crx
